name: test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nixpkgs/nix-flakes:nixos-22.11
    steps:
      - name: use exa
        run: nix shell nixpkgs#exa -c exa -l /

